# Site settings
title: "Ahmad Haghighi"
subtitle: "احمد حقیقی"
email: haghighi.ahmad@gmail.com
description: "Ahmad Haghighi’s personal page."
baseurl: ""
url: "https://ahmadhaghighi.com"
title_description: "Ahmad Haghighi’s personal page."
bio: "| Free Software advocate | GNU/Linux sysadmin | Programmer |"
title_image: "assets/images/mypic.jpg"
# google_analytics: ""
disqus_account: haghighi
github_repository: https://github.com/haghighi-ahmad
#addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: haghighi_ahmad
telegram_username: haghighi_ahmad
github_username:  haghighi-ahmad
mastodon_username:  haghighi
gitlab_username:  haghighi-ahmad
fedora_username:  Haghighi
linkedin_link: https://www.linkedin.com/in/ahmadhaghighi
#stackoverflow_link: https://www.stackoverflow.com/users/2174408/mrrolling

# Footer
footer_left: "Made with <i class=\"fas fa-coffee\"></i> in Naboo."
# footer_right: "&lt;/&gt; on <a href=\"https://github.com/haghighi-ahmad\">Github</a> &nbsp;<i class=\"fab fa-github\"></i>"
footer_right: 'Copyright © 2019 Ahmad Haghighi.'
footer_center: '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="/assets/images/by-sa-88x31.png" /></a> Posts and Articles are licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0 International License</a>.'
# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:categories/:year/:title/
exclude: [vendor]
